#ifndef __DALI_TEXT_ABSTRACTION_DEFINITIONS_H__
#define __DALI_TEXT_ABSTRACTION_DEFINITIONS_H__

/*
 * Copyright (c) 2015 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// EXTERNAL INCLUDES
#include <stdint.h>

namespace Dali
{

namespace TextAbstraction
{

typedef uint32_t FontId;          ///< The unique identifier for a font face (generated by FontClient)
typedef uint32_t PointSize26Dot6; ///< The point size in 26.6 fractional points
typedef uint32_t FaceIndex;       ///< Used with fonts which allow several font faces
typedef uint32_t GlyphIndex;      ///< Uniquely identifies a glyph within a particular font
typedef uint32_t Character;       ///< A UTF-32 representation of a character
typedef uint32_t CharacterIndex;  ///< An index into an array of characters
typedef uint32_t Length;          ///< The length of an array
typedef uint32_t BidiInfoIndex;   ///< Index to the bidirectional info for a paragraph.
typedef char     LineBreakInfo;   ///< Line break info (must break, allow break, no break).
typedef char     WordBreakInfo;   ///< Word break info (break, no break).

/**
 * @brief Enumerates the possible line break info values.
 */
enum
{
  LINE_MUST_BREAK  = 0u, ///< Text must be broken into a new line.
  LINE_ALLOW_BREAK = 1u, ///< Is possible to break the text into a new line.
  LINE_NO_BREAK    = 2u  ///< Text can't be broken into a new line.
};

/**
 * @brief Enumerates the possible word break info values.
 */
enum
{
  WORD_BREAK    = 0u, ///< Text can be broken into a new word.
  WORD_NO_BREAK = 1u, ///< Text can't be broken into a new word.
};

/*
 * @brief Script is the writing system used by a language.
 * Typically one script can be used to write different languages although one language could be written in different scrips.
 */
enum Script
{
  LATIN,      ///< The latin script. Used by many western languages and others around the world.
  ARABIC,     ///< The arabic script. Used by Arab and Urdu among others.
  DEVANAGARI, ///< The devanagari script. Used by Hindi, Marathi, Sindhi, Nepali and Sanskrit.
  BENGALI,    ///< The Bengali script. Used by Bangla, Assamese, Bishnupriya Manipuri, Daphla, Garo, Hallam, Khasi, Mizo, Munda, Naga, Rian, and Santali.
  GURMUKHI,   ///< The Gurmukhi script. Used by Punjabi.
  GUJARATI,   ///< The Gujarati script. Used by Gujarati.
  ORIYA,      ///< The Oriya script. Used by Oriya (Odia), Khondi, and Santali.
  TAMIL,      ///< The Tamil script. Used by Tamil, Badaga, and Saurashtra.
  TELUGU,     ///< The Telugu script. Used by Telugu, Gondi, and Lambadi.
  KANNADA,    ///< The Kannada script. Used by Kannada and Tulu.
  MALAYALAM,  ///< The Malayalam script. Used by Malayalam.
  SINHALA,    ///< The Sinhala script. Used by Sinhala and Pali.
  CJK,        ///< The CJK script. Used by Chinese, Japanese, Korean and Vietnamese(old writing system).
  HANGUL,     ///< The Hangul jamo script. Used by Korean.
  KHMER,      ///< The Khmer script. Used by the Khmer language.
  LAO,        ///< The Lao script. Used by the Lao language.
  THAI,       ///< The Thai script. Used by the Thai language
  BURMESE,    ///< The Burmese script. Used by the Burmese (Myanmar) language.
  UNKNOWN     ///< The script is unknown.
};

} // namespace TextAbstraction

} // namespace Dali

#endif // __DALI_TEXT_ABSTRACTION_DEFINITIONS_H__
