/**
 * Generated by tidlc 2.9.3.
 */

#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

#include "view-stub.h"

#include <assert.h>
#include <dlog.h>
#include <stdlib.h>

#include <app_common.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <libgen.h>
#include <glib.h>
#include <dlog.h>
#include <dlfcn.h>
#include <rpc-port.h>
#include <rpc-port-parcel.h>
#include <unistd.h>

#include <map>
#include <memory>
#include <set>
#include <string>
#include <stdexcept>
#include <utility>
#include <unordered_map>

#undef LOG_TAG
#define LOG_TAG "RPC_PORT_STUB"

#undef _E
#define _E(fmt, ...) dlog_print(DLOG_ERROR, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _W
#define _W(fmt, ...) dlog_print(DLOG_WARN, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _I
#define _I(fmt, ...) dlog_print(DLOG_INFO, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef _D
#define _D(fmt, ...) dlog_print(DLOG_DEBUG, LOG_TAG, "%s: %s(%d) > " fmt, basename(const_cast<char*>(__FILE__)), __FUNCTION__, __LINE__, ##__VA_ARGS__)

#undef TIDL_VERSION
#define TIDL_VERSION "2.9.3"

#undef TIDL_VER_MAJOR
#define TIDL_VER_MAJOR 2

#undef TIDL_VER_MINOR
#define TIDL_VER_MINOR 9

#undef TIDL_VER_PATCH
#define TIDL_VER_PATCH 3

#undef EXPORT_API
#define EXPORT_API extern "C" __attribute__ ((visibility("default")))

namespace {

constexpr const uid_t kRegularUidMin = 5000;

bool IdleAddOnce(GMainContext* context, std::function<void()>* func) {
  auto* source = g_idle_source_new();
  if (source == nullptr) {
    _E("Failed to create idle source");
    return false;
  }

  g_source_set_callback(source, static_cast<GSourceFunc>(
  [](gpointer user_data) {
    auto* cb = static_cast<std::function<void()>*>(user_data);
    (*cb)();
    delete cb;
    return G_SOURCE_REMOVE;
  }), func, nullptr);
  g_source_attach(source, context);
  g_source_unref(source);
  return true;
}

std::shared_ptr<rpc_port::implview::LocalExecution> TizenActionView_context_;

typedef enum {
  RPC_PORT_PARCEL_HEADER_UNKNOWN = 0b00000000,
  RPC_PORT_PARCEL_HEADER_IS_FROM_PROXY = 0b00000011,
  RPC_PORT_PARCEL_HEADER_LAN_C = 0b00000101,
  RPC_PORT_PARCEL_HEADER_LAN_CPP = 0b00001001,
  RPC_PORT_PARCEL_HEADER_LAN_CS = 0b00001101,
  RPC_PORT_PARCEL_HEADER_LAN_RUST = 0b00010001,
  RPC_PORT_PARCEL_HEADER_LAN_DART = 0b00010101,
} rpc_port_parcel_header_flags_e;

using rpc_port_parcel_reserve_t = int (*)(rpc_port_parcel_h h, unsigned int size);

using rpc_port_parcel_create_from_parcel_t = int (*)(rpc_port_parcel_h* h,
rpc_port_parcel_h origin_parcel,
unsigned int start_pos,
unsigned int size);
using rpc_port_parcel_set_data_size_t = int (*)(rpc_port_parcel_h h, unsigned int size);
using rpc_port_parcel_get_data_size_t = int (*)(rpc_port_parcel_h h, unsigned int* size);
using rpc_port_parcel_pin_t = int (*)(rpc_port_parcel_h h);
using rpc_port_parcel_get_reader_t = int (*)(rpc_port_parcel_h h, unsigned int* reader_pos);
using rpc_port_parcel_set_reader_t = int (*)(rpc_port_parcel_h h, unsigned int reader_pos);
using rpc_port_parcel_write_fd_t = int (*)(rpc_port_parcel_h h, int fd);
using rpc_port_parcel_read_fd_t = int (*)(rpc_port_parcel_h h, int* fd);
using rpc_port_parcel_clone_t = int (*)(rpc_port_parcel_h* h, rpc_port_parcel_h origin);
using rpc_port_get_peer_info_t = int (*)(rpc_port_h h, pid_t* pid, uid_t* uid);
using rpc_port_get_read_fd_t = int (*)(rpc_port_h h, int* fd);
using rpc_port_stub_has_pending_request_t = int (*)(rpc_port_stub_h h, bool* has_request);

using rpc_port_stub_has_privilege_local_t = int (*)(rpc_port_stub_h h, const char *appid, const char *privilege, bool *has_privilege);
using rpc_port_parcel_header_set_tag_ex_t = int (*)(rpc_port_parcel_header_h header,
unsigned char tidlc_version_major,
unsigned char tidlc_version_minor,
unsigned char tidlc_version_patch,
unsigned char tidl_protocol_ver,
unsigned char flags);
using rpc_port_parcel_header_get_tag_ex_t = int (*)(rpc_port_parcel_header_h header,
unsigned char* tidlc_version_major,
unsigned char* tidlc_version_minor,
unsigned char* tidlc_version_patch,
unsigned char* tidl_protocol_ver,
unsigned char* flags);

rpc_port_parcel_reserve_t dl_rpc_port_parcel_reserve;
rpc_port_parcel_create_from_parcel_t dl_rpc_port_parcel_create_from_parcel;
rpc_port_parcel_set_data_size_t dl_rpc_port_parcel_set_data_size;
rpc_port_parcel_get_data_size_t dl_rpc_port_parcel_get_data_size;
rpc_port_parcel_pin_t dl_rpc_port_parcel_pin;
rpc_port_parcel_get_reader_t dl_rpc_port_parcel_get_reader;
rpc_port_parcel_set_reader_t dl_rpc_port_parcel_set_reader;
rpc_port_parcel_write_fd_t dl_rpc_port_parcel_write_fd;
rpc_port_parcel_read_fd_t dl_rpc_port_parcel_read_fd;
rpc_port_parcel_clone_t dl_rpc_port_parcel_clone;
rpc_port_get_peer_info_t dl_rpc_port_get_peer_info;
rpc_port_get_read_fd_t dl_rpc_port_get_read_fd;
rpc_port_stub_has_pending_request_t dl_rpc_port_stub_has_pending_request;
rpc_port_parcel_header_set_tag_ex_t dl_rpc_port_parcel_header_set_tag_ex;
rpc_port_parcel_header_get_tag_ex_t dl_rpc_port_parcel_header_get_tag_ex;
rpc_port_stub_has_privilege_local_t dl_rpc_port_stub_has_privilege_local;

class RpcPortInternals {
 public:
  RpcPortInternals() {
    std::string symbol = "rpc_port_parcel_reserve";
    dl_rpc_port_parcel_reserve = reinterpret_cast<rpc_port_parcel_reserve_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_reserve == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_create_from_parcel";
    dl_rpc_port_parcel_create_from_parcel = reinterpret_cast<rpc_port_parcel_create_from_parcel_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_create_from_parcel == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_set_data_size";
    dl_rpc_port_parcel_set_data_size =
    reinterpret_cast<rpc_port_parcel_set_data_size_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_set_data_size == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_get_data_size";
    dl_rpc_port_parcel_get_data_size =
    reinterpret_cast<rpc_port_parcel_get_data_size_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_get_data_size == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_pin";
    dl_rpc_port_parcel_pin = reinterpret_cast<rpc_port_parcel_pin_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_pin == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_get_reader";
    dl_rpc_port_parcel_get_reader = reinterpret_cast<rpc_port_parcel_get_reader_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_get_reader == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_set_reader";
    dl_rpc_port_parcel_set_reader = reinterpret_cast<rpc_port_parcel_set_reader_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_set_reader == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_write_fd";
    dl_rpc_port_parcel_write_fd = reinterpret_cast<rpc_port_parcel_write_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_write_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_read_fd";
    dl_rpc_port_parcel_read_fd = reinterpret_cast<rpc_port_parcel_read_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_read_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_clone";
    dl_rpc_port_parcel_clone = reinterpret_cast<rpc_port_parcel_clone_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_clone == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_get_peer_info";
    dl_rpc_port_get_peer_info = reinterpret_cast<rpc_port_get_peer_info_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_get_peer_info == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_get_read_fd";
    dl_rpc_port_get_read_fd = reinterpret_cast<rpc_port_get_read_fd_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_get_read_fd == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_stub_has_pending_request";
    dl_rpc_port_stub_has_pending_request = reinterpret_cast<rpc_port_stub_has_pending_request_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if(dl_rpc_port_stub_has_pending_request == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }

    symbol = "rpc_port_parcel_header_set_tag_ex";
    dl_rpc_port_parcel_header_set_tag_ex = reinterpret_cast<rpc_port_parcel_header_set_tag_ex_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_header_set_tag_ex == nullptr) {
      _I("Failed to find symbol(%s). Ok, We will use old API", symbol.c_str());
    }

    symbol = "rpc_port_parcel_header_get_tag_ex";
    dl_rpc_port_parcel_header_get_tag_ex = reinterpret_cast<rpc_port_parcel_header_get_tag_ex_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_parcel_header_get_tag_ex == nullptr) {
      _I("Failed to find symbol(%s). Ok, We will use old API", symbol.c_str());
    }

    symbol = "rpc_port_stub_has_privilege_local";
    dl_rpc_port_stub_has_privilege_local = reinterpret_cast<rpc_port_stub_has_privilege_local_t>(
    dlsym(RTLD_DEFAULT, symbol.c_str()));
    if (dl_rpc_port_stub_has_privilege_local == nullptr) {
      _E("Failed to find symbol(%s). Please check rpc-port version", symbol.c_str());
      return;
    }
  }
};

RpcPortInternals rpc_port_internals_;

}  // namespace

namespace rpc_port {
namespace implview {

LocalExecution::LocalExecution(std::string port_name, LocalExecution::IEvent* listener) : port_name_(std::move(port_name)), listener_(listener), context_(g_main_context_ref_thread_default(), g_main_context_unref) {
  LoadSymbols();
}

void LocalExecution::Connect(void* context, bool sync) {
  if (connect_func_ != nullptr)
    connect_func_(context, sync);
}

void LocalExecution::Disconnect(void* context) {
  if (disconnect_func_ != nullptr)
    disconnect_func_(context);
}

void LocalExecution::SendResult(void* context, rpc_port_parcel_h parcel) {
  if (send_result_func_ != nullptr)
    send_result_func_(context, parcel);
}

void LocalExecution::InvokeCallback(void* context, rpc_port_parcel_h parcel) {
  if (invoke_callback_func_ != nullptr)
    invoke_callback_func_(context, parcel);
}

void LocalExecution::OnConnected(void* context, const std::string& sender, const std::string& instance, bool sync) {
  if (listener_ != nullptr)
    listener_->OnLocalConnected(context, sender, instance, sync);
}

void LocalExecution::OnDisconnected(void* context, const std::string& sender, const std::string& instance) {
  if (listener_ != nullptr)
    listener_->OnLocalDisconnected(context, sender, instance);
}

void LocalExecution::OnReceived(void* context, rpc_port_parcel_h parcel) {
  if (listener_ != nullptr)
    listener_->OnLocalReceived(context, parcel);
}

bool LocalExecution::LoadSymbols() {
  if (loaded_)
    return true;

  std::string symbol = "rpc_port_proxy_tizen_action_view_lem_" + port_name_ + "_connect";
  connect_func_ = reinterpret_cast<ProxyConnectFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (connect_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_view_lem_" + port_name_ + "_disconnect";
  disconnect_func_ = reinterpret_cast<ProxyDisconnectFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (disconnect_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_view_lem_" + port_name_ + "_send_result";
  send_result_func_ = reinterpret_cast<ProxySendResultFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (send_result_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  symbol = "rpc_port_proxy_tizen_action_view_lem_" + port_name_ + "_invoke_callback";
  invoke_callback_func_ = reinterpret_cast<ProxyInvokeCallbackFunc>(dlsym(RTLD_DEFAULT, symbol.c_str()));
  if (invoke_callback_func_ == nullptr) {
    _E("Failed to find symbol");
    return false;
  }

  loaded_ = true;
  return true;
}

void LocalExecution::SetListening(bool listening) {
  listening_ = listening;
}

bool LocalExecution::IsListening() const {
  return listening_;
}

GMainContext* LocalExecution::GetContext() const { return context_.get(); }

Bundle::Bundle() {
  handle_ = bundle_create();
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle::Bundle(bundle* handle, bool copy, bool own) : handle_(handle), own_(own) {
  if (handle == nullptr)
    throw std::invalid_argument("handle is nullptr");

  if (copy) {
    handle_ = bundle_dup(handle);
    if (handle_ == nullptr)
      throw std::bad_alloc();
  }
}

Bundle::Bundle(std::string raw) {
  handle_ = bundle_decode(reinterpret_cast<const bundle_raw*>(raw.c_str()), raw.length());
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle::~Bundle() {
  if (own_ && handle_)
    bundle_free(handle_);
}

Bundle::Bundle(const Bundle& b) {
  handle_ = bundle_dup(b.handle_);
  if (handle_ == nullptr)
    throw std::bad_alloc();
}

Bundle& Bundle::operator = (const Bundle& b) {
  if (this != &b) {
    if (handle_ && own_)
      bundle_free(handle_);

    handle_ = bundle_dup(b.handle_);
    if (handle_ == nullptr)
      throw std::bad_alloc();

    own_ = true;
  }

  return *this;
}

Bundle::Bundle(Bundle&& b) noexcept {
  handle_ = b.handle_;
  b.handle_ = bundle_create();
  own_ = b.own_;
  b.own_ = true;
}

Bundle& Bundle::operator = (Bundle&& b) noexcept {
  if (this != &b) {
    if (handle_ && own_)
      bundle_free(handle_);

    handle_ = b.handle_;
    b.handle_ = bundle_create();
    own_ = b.own_;
  }

  return *this;
}

bundle* Bundle::GetHandle() const {
  return handle_;
}

bundle* Bundle::Detach() {
  bundle* handle = handle_;
  handle_ = nullptr;
  return handle;
}

File::File(std::string filename) : filename_(std::move(filename)) {}

const std::string& File::GetFileName() const {
  return filename_;
}

int File::Share(rpc_port_h port) {
  int ret = rpc_port_set_private_sharing(port, filename_.c_str());
  if (ret != RPC_PORT_ERROR_NONE)
    _E("Failed to set private sharing. error(%d)", ret);

  return ret;
}

constexpr char kJsonObjOpen = 0x7b;
constexpr char kJsonObjClose = 0x7d;

inline std::string JsonEscape(const std::string& str) {
  static const char hex[] = "0123456789abcdef";
  std::string ret;
  for (const auto& ch : str) {
    if (ch == '"') {
      ret += "\\\"";
      continue;
    }

    if (ch == '\\') {
      ret += "\\\\";
      continue;
    }

    if (ch == '\b') {
      ret += "\\b";
      continue;
    }

    if (ch == '\f') {
      ret += "\\f";
      continue;
    }

    if (ch == '\n') {
      ret += "\\n";
      continue;
    }

    if (ch == '\r') {
      ret += "\\r";
      continue;
    }

    if (ch == '\t') {
      ret += "\\t";
      continue;
    }

    if (static_cast<unsigned char>(ch) < 0x20) {
      ret += "\\u00";
      ret += hex[(ch >> 4) & 0xf];
      ret += hex[ch & 0xf];
      continue;
    }

    ret += ch;
  }

  return ret;
}

inline void AppendToJson(std::string& json_str, bool value);
inline void AppendToJson(std::string& json_str, char value);
inline void AppendToJson(std::string& json_str, short value);
inline void AppendToJson(std::string& json_str, int value);
inline void AppendToJson(std::string& json_str, long long value);
inline void AppendToJson(std::string& json_str, unsigned char value);
inline void AppendToJson(std::string& json_str, unsigned short value);
inline void AppendToJson(std::string& json_str, unsigned int value);
inline void AppendToJson(std::string& json_str, unsigned long value);
inline void AppendToJson(std::string& json_str, float value);
inline void AppendToJson(std::string& json_str, double value);
inline void AppendToJson(std::string& json_str, const std::string& value);
inline void AppendToJson(std::string& json_str, const Bundle& value);
template <class T>
void AppendToJson(std::string& json_str, const std::list<T>& value);
template <class T>
void AppendToJson(std::string& json_str, const std::vector<T>& value);
template <class T>
void AppendToJson(std::string& json_str, const std::set<T>& value);
template <class K, class V>
void AppendToJson(std::string& json_str, const std::map<K, V>& value);
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.ToJson(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.GetFileName(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.Get(), void());
template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(static_cast<long long>(value), void());

inline void AppendToJson(std::string& json_str, bool value) {
  json_str += value ? "true" : "false";
}

inline void AppendToJson(std::string& json_str, char value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, short value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, int value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, long long value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned char value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned short value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned int value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, unsigned long value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, float value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, double value) {
  json_str += std::to_string(value);
}

inline void AppendToJson(std::string& json_str, const std::string& value) {
  json_str += "\"" + JsonEscape(value) + "\"";
}

inline void AppendToJson(std::string& json_str, const Bundle& value) {
  bundle_raw* raw = nullptr;
  int len = 0;
  bundle_encode(value.GetHandle(), &raw, &len);
  if (raw == nullptr) {
    json_str += "null";
    return;
  }

  json_str += "\"" + JsonEscape(std::string(reinterpret_cast<const char*>(raw), len)) + "\"";
  free(raw);
}

template <class T>
void AppendToJson(std::string& json_str, const std::list<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class T>
void AppendToJson(std::string& json_str, const std::vector<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class T>
void AppendToJson(std::string& json_str, const std::set<T>& value) {
  json_str += "[";
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    AppendToJson(json_str, i);
  }

  json_str += "]";
}

template <class K, class V>
void AppendToJson(std::string& json_str, const std::map<K, V>& value) {
  json_str += kJsonObjOpen;
  bool first = true;
  for (const auto& i : value) {
    if (!first) json_str += ",";
    first = false;
    std::string key_str;
    AppendToJson(key_str, i.first);
    if (key_str.empty() || key_str.front() != '"')
      key_str = "\"" + key_str + "\"";

    json_str += key_str + ":";
    AppendToJson(json_str, i.second);
  }

  json_str += kJsonObjClose;
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.ToJson(), void()) {
  json_str += value.ToJson();
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.GetFileName(), void()) {
  json_str += "\"" + JsonEscape(value.GetFileName()) + "\"";
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(value.Get(), void()) {
  json_str += std::to_string(value.Get());
}

template <class T>
auto AppendToJson(std::string& json_str, const T& value)
-> decltype(static_cast<long long>(value), void()) {
  json_str += std::to_string(static_cast<long long>(value));
}

TizenEntityPresentation::TizenEntityPresentation() {}

TizenEntityPresentation::TizenEntityPresentation(std::string Document, std::string Template) : Document_(std::move(Document)), Template_(std::move(Template)) {}

const std::string& TizenEntityPresentation::GetDocument() const {
  return Document_;
}

void TizenEntityPresentation::SetDocument(std::string Document) {
  Document_ = std::move(Document);
}

const std::string& TizenEntityPresentation::GetTemplate() const {
  return Template_;
}

void TizenEntityPresentation::SetTemplate(std::string Template) {
  Template_ = std::move(Template);
}

std::string TizenEntityPresentation::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityPresentation\":";
  json_str += kJsonObjOpen;
  json_str += "\"Document\":";
  AppendToJson(json_str, GetDocument());
  json_str += ",\"Template\":";
  AppendToJson(json_str, GetTemplate());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityStatus::TizenEntityStatus() : Success_(false) {}

TizenEntityStatus::TizenEntityStatus(bool Success, std::string Reason) : Success_(Success), Reason_(std::move(Reason)) {}

bool TizenEntityStatus::GetSuccess() const {
  return Success_;
}

void TizenEntityStatus::SetSuccess(bool Success) {
  Success_ = Success;
}

const std::string& TizenEntityStatus::GetReason() const {
  return Reason_;
}

void TizenEntityStatus::SetReason(std::string Reason) {
  Reason_ = std::move(Reason);
}

std::string TizenEntityStatus::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityStatus\":";
  json_str += kJsonObjOpen;
  json_str += "\"Success\":";
  AppendToJson(json_str, GetSuccess());
  json_str += ",\"Reason\":";
  AppendToJson(json_str, GetReason());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntity::TizenEntity() {}

TizenEntity::TizenEntity(std::string Id, std::string Extra) : Id_(std::move(Id)), Extra_(std::move(Extra)) {}

const std::string& TizenEntity::GetId() const {
  return Id_;
}

void TizenEntity::SetId(std::string Id) {
  Id_ = std::move(Id);
}

const std::string& TizenEntity::GetExtra() const {
  return Extra_;
}

void TizenEntity::SetExtra(std::string Extra) {
  Extra_ = std::move(Extra);
}

std::string TizenEntity::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntity\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

ScreenBounds::ScreenBounds() : X_(0.0), Y_(0.0), Width_(0.0), Height_(0.0) {}

ScreenBounds::ScreenBounds(double X, double Y, double Width, double Height) : X_(X), Y_(Y), Width_(Width), Height_(Height) {}

double ScreenBounds::GetX() const {
  return X_;
}

void ScreenBounds::SetX(double X) {
  X_ = X;
}

double ScreenBounds::GetY() const {
  return Y_;
}

void ScreenBounds::SetY(double Y) {
  Y_ = Y;
}

double ScreenBounds::GetWidth() const {
  return Width_;
}

void ScreenBounds::SetWidth(double Width) {
  Width_ = Width;
}

double ScreenBounds::GetHeight() const {
  return Height_;
}

void ScreenBounds::SetHeight(double Height) {
  Height_ = Height;
}

std::string ScreenBounds::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"ScreenBounds\":";
  json_str += kJsonObjOpen;
  json_str += "\"X\":";
  AppendToJson(json_str, GetX());
  json_str += ",\"Y\":";
  AppendToJson(json_str, GetY());
  json_str += ",\"Width\":";
  AppendToJson(json_str, GetWidth());
  json_str += ",\"Height\":";
  AppendToJson(json_str, GetHeight());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

WindowBounds::WindowBounds() : X_(0.0), Y_(0.0), Width_(0.0), Height_(0.0) {}

WindowBounds::WindowBounds(double X, double Y, double Width, double Height) : X_(X), Y_(Y), Width_(Width), Height_(Height) {}

double WindowBounds::GetX() const {
  return X_;
}

void WindowBounds::SetX(double X) {
  X_ = X;
}

double WindowBounds::GetY() const {
  return Y_;
}

void WindowBounds::SetY(double Y) {
  Y_ = Y;
}

double WindowBounds::GetWidth() const {
  return Width_;
}

void WindowBounds::SetWidth(double Width) {
  Width_ = Width;
}

double WindowBounds::GetHeight() const {
  return Height_;
}

void WindowBounds::SetHeight(double Height) {
  Height_ = Height;
}

std::string WindowBounds::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"WindowBounds\":";
  json_str += kJsonObjOpen;
  json_str += "\"X\":";
  AppendToJson(json_str, GetX());
  json_str += ",\"Y\":";
  AppendToJson(json_str, GetY());
  json_str += ",\"Width\":";
  AppendToJson(json_str, GetWidth());
  json_str += ",\"Height\":";
  AppendToJson(json_str, GetHeight());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

Annotation::Annotation() {}

Annotation::Annotation(std::string EntityId, std::string EntityType, std::string EntityInfo) : EntityId_(std::move(EntityId)), EntityType_(std::move(EntityType)), EntityInfo_(std::move(EntityInfo)) {}

const std::string& Annotation::GetEntityId() const {
  return EntityId_;
}

void Annotation::SetEntityId(std::string EntityId) {
  EntityId_ = std::move(EntityId);
}

const std::string& Annotation::GetEntityType() const {
  return EntityType_;
}

void Annotation::SetEntityType(std::string EntityType) {
  EntityType_ = std::move(EntityType);
}

const std::string& Annotation::GetEntityInfo() const {
  return EntityInfo_;
}

void Annotation::SetEntityInfo(std::string EntityInfo) {
  EntityInfo_ = std::move(EntityInfo);
}

std::string Annotation::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"Annotation\":";
  json_str += kJsonObjOpen;
  json_str += "\"EntityId\":";
  AppendToJson(json_str, GetEntityId());
  json_str += ",\"EntityType\":";
  AppendToJson(json_str, GetEntityType());
  json_str += ",\"EntityInfo\":";
  AppendToJson(json_str, GetEntityInfo());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

TizenEntityView::TizenEntityView() : IsFocused_(false), IsEnabled_(false) {}

TizenEntityView::TizenEntityView(std::string Id, std::string Extra, std::string Type, std::string Description, ScreenBounds ScreenBounds, WindowBounds WindowBounds, bool IsFocused, bool IsEnabled, Annotation Annotation) : TizenEntity(std::move(Id), std::move(Extra)), Type_(std::move(Type)), Description_(std::move(Description)), ScreenBounds_(std::move(ScreenBounds)), WindowBounds_(std::move(WindowBounds)), IsFocused_(IsFocused), IsEnabled_(IsEnabled), Annotation_(std::move(Annotation)) {}

const std::string& TizenEntityView::GetType() const {
  return Type_;
}

void TizenEntityView::SetType(std::string Type) {
  Type_ = std::move(Type);
}

const std::string& TizenEntityView::GetDescription() const {
  return Description_;
}

void TizenEntityView::SetDescription(std::string Description) {
  Description_ = std::move(Description);
}

const ScreenBounds& TizenEntityView::GetScreenBounds() const {
  return ScreenBounds_;
}

void TizenEntityView::SetScreenBounds(ScreenBounds ScreenBounds) {
  ScreenBounds_ = std::move(ScreenBounds);
}

const WindowBounds& TizenEntityView::GetWindowBounds() const {
  return WindowBounds_;
}

void TizenEntityView::SetWindowBounds(WindowBounds WindowBounds) {
  WindowBounds_ = std::move(WindowBounds);
}

bool TizenEntityView::GetIsFocused() const {
  return IsFocused_;
}

void TizenEntityView::SetIsFocused(bool IsFocused) {
  IsFocused_ = IsFocused;
}

bool TizenEntityView::GetIsEnabled() const {
  return IsEnabled_;
}

void TizenEntityView::SetIsEnabled(bool IsEnabled) {
  IsEnabled_ = IsEnabled;
}

const Annotation& TizenEntityView::GetAnnotation() const {
  return Annotation_;
}

void TizenEntityView::SetAnnotation(Annotation Annotation) {
  Annotation_ = std::move(Annotation);
}

std::string TizenEntityView::ToJson() const {
  std::string json_str;
  json_str += kJsonObjOpen;
  json_str += "\"TizenEntityView\":";
  json_str += kJsonObjOpen;
  json_str += "\"Id\":";
  AppendToJson(json_str, GetId());
  json_str += ",\"Extra\":";
  AppendToJson(json_str, GetExtra());
  json_str += ",\"Type\":";
  AppendToJson(json_str, GetType());
  json_str += ",\"Description\":";
  AppendToJson(json_str, GetDescription());
  json_str += ",\"ScreenBounds\":";
  AppendToJson(json_str, GetScreenBounds());
  json_str += ",\"WindowBounds\":";
  AppendToJson(json_str, GetWindowBounds());
  json_str += ",\"IsFocused\":";
  AppendToJson(json_str, GetIsFocused());
  json_str += ",\"IsEnabled\":";
  AppendToJson(json_str, GetIsEnabled());
  json_str += ",\"Annotation\":";
  AppendToJson(json_str, GetAnnotation());

  json_str += kJsonObjClose;
  json_str += kJsonObjClose;
  return json_str;
}

namespace stub {

RemoteException::RemoteException() {}

RemoteException::RemoteException(std::string message) : message_(std::move(message)) {}

RemoteException::RemoteException(int cause, std::string message) : cause_(cause), message_(std::move(message)) {}

int RemoteException::GetCause() const {
  return cause_;
}

const std::string& RemoteException::GetMessage() const {
  return message_;
}

class Unit {
 public:
  Unit() {}

  Unit(int32_t name, int32_t type) : name_(name), type_(type) {}

  const int32_t& GetName() const { return name_; }

  void SetName(int32_t name) { name_ = name; }

  const int32_t& GetType() const { return type_; }

  void SetType(int32_t type) { type_ = type; }

  void Serialize(rpc_port_parcel_h parcel) {
    rpc_port_parcel_write_int32(parcel, name_);
    rpc_port_parcel_write_int32(parcel, type_);

    unsigned int size_pos = 0;
    dl_rpc_port_parcel_get_data_size(parcel, &size_pos);
    dl_rpc_port_parcel_reserve(parcel, sizeof(unsigned int));

    for (auto& i : cmds_) {
      i(parcel);
    }

    unsigned int cur_pos;
    dl_rpc_port_parcel_get_data_size(parcel, &cur_pos);
    size_t size = cur_pos - size_pos - sizeof(unsigned int);
    dl_rpc_port_parcel_set_data_size(parcel, size_pos);
    rpc_port_parcel_write_int32(parcel, size);
    dl_rpc_port_parcel_set_data_size(parcel, cur_pos);
    cmds_.clear();
  }

  void Deserialize(rpc_port_parcel_h parcel) {
    rpc_port_parcel_read_int32(parcel, reinterpret_cast<int*>(&name_));
    rpc_port_parcel_read_int32(parcel, reinterpret_cast<int*>(&type_));

    int size = 0;
    rpc_port_parcel_read_array_count(parcel, &size);
    if (size == 0) return;

    uint32_t start_pos = 0;
    dl_rpc_port_parcel_get_reader(parcel, &start_pos);

    rpc_port_parcel_h sub_parcel_raw = nullptr;
    dl_rpc_port_parcel_create_from_parcel(&sub_parcel_raw, parcel, start_pos,
    size);
    sub_parcel_.reset(sub_parcel_raw);
    dl_rpc_port_parcel_reserve(sub_parcel_.get(), size);
    dl_rpc_port_parcel_set_reader(parcel, start_pos + size);
  }

  void Write(const std::vector<TizenEntityView>& value, rpc_port_parcel_h parcel = nullptr);
  void Read(std::vector<TizenEntityView>& value);

  void Write(const TizenActionView::CallbackBase& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenActionView::CallbackBase& value);

  void Write(const TizenEntityView& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityView& value);

  void Write(const ScreenBounds& value, rpc_port_parcel_h parcel = nullptr);
  void Read(ScreenBounds& value);

  void Write(const int& value, rpc_port_parcel_h parcel = nullptr);
  void Read(int& value);

  void Write(const WindowBounds& value, rpc_port_parcel_h parcel = nullptr);
  void Read(WindowBounds& value);

  void Write(const TizenEntity& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntity& value);

  void Write(const bool& value, rpc_port_parcel_h parcel = nullptr);
  void Read(bool& value);

  void Write(const std::string& value, rpc_port_parcel_h parcel = nullptr);
  void Read(std::string& value);

  void Write(const Bundle& value, rpc_port_parcel_h parcel = nullptr);
  void Read(Bundle& value);

  void Write(const RemoteException& value, rpc_port_parcel_h parcel = nullptr);
  void Read(RemoteException& value);

  void Write(const File& value, rpc_port_parcel_h parcel = nullptr);
  void Read(File& value);

  void Write(const TizenEntityPresentation& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityPresentation& value);

  void Write(const TizenEntityStatus& value, rpc_port_parcel_h parcel = nullptr);
  void Read(TizenEntityStatus& value);

  void Write(const double& value, rpc_port_parcel_h parcel = nullptr);
  void Read(double& value);

  void Write(const Annotation& value, rpc_port_parcel_h parcel = nullptr);
  void Read(Annotation& value);

 private:
  int32_t name_ = 0;
  int32_t type_ = 0;
  std::vector<std::function<void(rpc_port_parcel_h)>> cmds_;
  std::unique_ptr<std::remove_pointer_t<rpc_port_parcel_h>,
  decltype(rpc_port_parcel_destroy)*>
  sub_parcel_{nullptr, rpc_port_parcel_destroy};
};

class UnitMap {
 public:
  UnitMap() {}

  void Clear() { map_.clear(); }

  size_t GetSize() const { return map_.size(); }

  void Insert(int32_t name, std::shared_ptr<Unit> unit) {
    map_[name] = std::move(unit);
  }

  std::shared_ptr<Unit> Lookup(int32_t name) const {
    auto found = map_.find(name);
    if (found == map_.end()) return nullptr;

    return found->second;
  }

  void Serialize(rpc_port_parcel_h parcel) const && {
    rpc_port_parcel_write_array_count(parcel, GetSize() & INT_MAX);
    for (auto& iter : map_) {
      auto& unit = iter.second;
      unit->Serialize(parcel);
    }
  }

  void Deserialize(rpc_port_parcel_h parcel) {
    int size = 0;
    rpc_port_parcel_read_array_count(parcel, &size);
    dl_rpc_port_parcel_pin(parcel);
    for (int i = 0; i < size; ++i) {
      auto unit = std::make_shared<Unit>();
      unit->Deserialize(parcel);
      auto name = unit->GetName();
      Insert(name, std::move(unit));
    }
  }

  void Read(int32_t name, std::vector<TizenEntityView>& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1094159920 /*array_TizenEntityView*/) {
      _E("type(%d) is not -1094159920", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const std::vector<TizenEntityView>& value) && {
    auto unit = std::make_shared<Unit>(name, -1094159920 /*array_TizenEntityView*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenActionView::CallbackBase& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 819322245 /*delegate*/) {
      _E("type(%d) is not 819322245", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenActionView::CallbackBase& value) && {
    auto unit = std::make_shared<Unit>(name, 819322245 /*delegate*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityView& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1014526171 /*TizenEntity::TizenEntityView*/) {
      _E("type(%d) is not -1014526171", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityView& value) && {
    auto unit = std::make_shared<Unit>(name, -1014526171 /*TizenEntity::TizenEntityView*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, ScreenBounds& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -2005600671 /*ScreenBounds*/) {
      _E("type(%d) is not -2005600671", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const ScreenBounds& value) && {
    auto unit = std::make_shared<Unit>(name, -2005600671 /*ScreenBounds*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, int& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 104431 /*int*/) {
      _E("type(%d) is not 104431", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const int& value) && {
    auto unit = std::make_shared<Unit>(name, 104431 /*int*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, WindowBounds& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1441702171 /*WindowBounds*/) {
      _E("type(%d) is not -1441702171", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const WindowBounds& value) && {
    auto unit = std::make_shared<Unit>(name, -1441702171 /*WindowBounds*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntity& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -393351823 /*TizenEntity*/) {
      _E("type(%d) is not -393351823", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntity& value) && {
    auto unit = std::make_shared<Unit>(name, -393351823 /*TizenEntity*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, bool& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 3029738 /*bool*/) {
      _E("type(%d) is not 3029738", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const bool& value) && {
    auto unit = std::make_shared<Unit>(name, 3029738 /*bool*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, std::string& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -891985903 /*string*/) {
      _E("type(%d) is not -891985903", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const std::string& value) && {
    auto unit = std::make_shared<Unit>(name, -891985903 /*string*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, Bundle& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1377881982 /*bundle*/) {
      _E("type(%d) is not -1377881982", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const Bundle& value) && {
    auto unit = std::make_shared<Unit>(name, -1377881982 /*bundle*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, RemoteException& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1223777386 /*remote_exception*/) {
      _E("type(%d) is not -1223777386", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const RemoteException& value) && {
    auto unit = std::make_shared<Unit>(name, -1223777386 /*remote_exception*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, File& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 3143036 /*file*/) {
      _E("type(%d) is not 3143036", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const File& value) && {
    auto unit = std::make_shared<Unit>(name, 3143036 /*file*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityPresentation& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 1161731883 /*TizenEntityPresentation*/) {
      _E("type(%d) is not 1161731883", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityPresentation& value) && {
    auto unit = std::make_shared<Unit>(name, 1161731883 /*TizenEntityPresentation*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, TizenEntityStatus& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1652879165 /*TizenEntityStatus*/) {
      _E("type(%d) is not -1652879165", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const TizenEntityStatus& value) && {
    auto unit = std::make_shared<Unit>(name, -1652879165 /*TizenEntityStatus*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, double& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != -1325958191 /*double*/) {
      _E("type(%d) is not -1325958191", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const double& value) && {
    auto unit = std::make_shared<Unit>(name, -1325958191 /*double*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

  void Read(int32_t name, Annotation& value) const {
    auto unit = Lookup(name);
    if (unit == nullptr) {
      _E("Failed to find %d", name);
      return;
    }

    if (unit->GetType() != 438421327 /*Annotation*/) {
      _E("type(%d) is not 438421327", unit->GetType());
      return;
    }

    unit->Read(value);
  }

  UnitMap&& Write(int32_t name, const Annotation& value) && {
    auto unit = std::make_shared<Unit>(name, 438421327 /*Annotation*/);
    unit->Write(value);
    Insert(name, std::move(unit));
    return std::move(*this);
  }

 private:
  std::unordered_map<int32_t, std::shared_ptr<Unit>> map_;
};

void Unit::Write(const std::vector<TizenEntityView>& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_array_count(p, static_cast<int>(value.size() & INT_MAX));

    for (auto& i : value)
      Write(i, p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(std::vector<TizenEntityView>& value) {
  int tmp_size = 0;
  rpc_port_parcel_read_array_count(sub_parcel_.get(), &tmp_size);

  for (int index = 0; index < tmp_size; ++index) {
    TizenEntityView tmp_value;
    Read(tmp_value);
    value.push_back(tmp_value);
  }

}

void Unit::Write(const TizenActionView::CallbackBase& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_int32(p, value.GetId());
    rpc_port_parcel_write_int32(p, value.GetSeqId());
    rpc_port_parcel_write_bool(p, value.IsOnce());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenActionView::CallbackBase& value) {
  int id = 0;
  int seq_id = 0;
  bool once = false;

  rpc_port_parcel_read_int32(sub_parcel_.get(), &id);
  rpc_port_parcel_read_int32(sub_parcel_.get(), &seq_id);
  rpc_port_parcel_read_bool(sub_parcel_.get(), &once);

  value.SetId(id);
  value.SetSeqId(seq_id);
  value.SetOnce(once);

}

void Unit::Write(const TizenEntityView& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

    Write(value.GetType(), p);

    Write(value.GetDescription(), p);

    Write(value.GetScreenBounds(), p);

    Write(value.GetWindowBounds(), p);

    Write(value.GetIsFocused(), p);

    Write(value.GetIsEnabled(), p);

    Write(value.GetAnnotation(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityView& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

  std::string tmp_Type;
  Read(tmp_Type);
  value.SetType(tmp_Type);

  std::string tmp_Description;
  Read(tmp_Description);
  value.SetDescription(tmp_Description);

  ScreenBounds tmp_ScreenBounds;
  Read(tmp_ScreenBounds);
  value.SetScreenBounds(tmp_ScreenBounds);

  WindowBounds tmp_WindowBounds;
  Read(tmp_WindowBounds);
  value.SetWindowBounds(tmp_WindowBounds);

  bool tmp_IsFocused = false;
  Read(tmp_IsFocused);
  value.SetIsFocused(tmp_IsFocused);

  bool tmp_IsEnabled = false;
  Read(tmp_IsEnabled);
  value.SetIsEnabled(tmp_IsEnabled);

  Annotation tmp_Annotation;
  Read(tmp_Annotation);
  value.SetAnnotation(tmp_Annotation);

}

void Unit::Write(const ScreenBounds& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetX(), p);

    Write(value.GetY(), p);

    Write(value.GetWidth(), p);

    Write(value.GetHeight(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(ScreenBounds& value) {
  double tmp_X = 0.0;
  Read(tmp_X);
  value.SetX(tmp_X);

  double tmp_Y = 0.0;
  Read(tmp_Y);
  value.SetY(tmp_Y);

  double tmp_Width = 0.0;
  Read(tmp_Width);
  value.SetWidth(tmp_Width);

  double tmp_Height = 0.0;
  Read(tmp_Height);
  value.SetHeight(tmp_Height);

}

void Unit::Write(const int& value, rpc_port_parcel_h parcel) {
  auto cb = [value, this](auto* p) {
    rpc_port_parcel_burst_write(p, reinterpret_cast<const unsigned char*>(&value), sizeof(int));

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(int& value) {
  int tmp_value = 0;
  rpc_port_parcel_burst_read(sub_parcel_.get(), reinterpret_cast<unsigned char*>(&tmp_value), sizeof(int));
  value = tmp_value;

}

void Unit::Write(const WindowBounds& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetX(), p);

    Write(value.GetY(), p);

    Write(value.GetWidth(), p);

    Write(value.GetHeight(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(WindowBounds& value) {
  double tmp_X = 0.0;
  Read(tmp_X);
  value.SetX(tmp_X);

  double tmp_Y = 0.0;
  Read(tmp_Y);
  value.SetY(tmp_Y);

  double tmp_Width = 0.0;
  Read(tmp_Width);
  value.SetWidth(tmp_Width);

  double tmp_Height = 0.0;
  Read(tmp_Height);
  value.SetHeight(tmp_Height);

}

void Unit::Write(const TizenEntity& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetId(), p);

    Write(value.GetExtra(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntity& value) {
  std::string tmp_Id;
  Read(tmp_Id);
  value.SetId(tmp_Id);

  std::string tmp_Extra;
  Read(tmp_Extra);
  value.SetExtra(tmp_Extra);

}

void Unit::Write(const bool& value, rpc_port_parcel_h parcel) {
  auto cb = [value, this](auto* p) {
    rpc_port_parcel_burst_write(p, reinterpret_cast<const unsigned char*>(&value), sizeof(bool));

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(bool& value) {
  bool tmp_value = false;
  rpc_port_parcel_burst_read(sub_parcel_.get(), reinterpret_cast<unsigned char*>(&tmp_value), sizeof(bool));
  value = tmp_value;

}

void Unit::Write(const std::string& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_string(p, value.c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(std::string& value) {
  char* tmp_str = nullptr;
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_str);
  if (tmp_str != nullptr) {
    value = std::string(tmp_str);
    free(tmp_str);
  }

}

void Unit::Write(const Bundle& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_bundle(p, value.GetHandle());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(Bundle& value) {
  bundle* tmp_b = nullptr;
  rpc_port_parcel_read_bundle(sub_parcel_.get(), &tmp_b);
  value = Bundle(tmp_b, false, true);

}

void Unit::Write(const RemoteException& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_int32(p, value.GetCause());
    rpc_port_parcel_write_string(p, value.GetMessage().c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(RemoteException& value) {
  char* tmp_str = nullptr;
  int cause = 0;
  std::string message;

  rpc_port_parcel_read_int32(sub_parcel_.get(), &cause);
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_str);
  if (tmp_str != nullptr) {
    message = tmp_str;
    free(tmp_str);
  }

  value = RemoteException(cause, std::move(message));

}

void Unit::Write(const File& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    rpc_port_parcel_write_string(p, value.GetFileName().c_str());

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(File& value) {
  char* tmp_filename = nullptr;
  rpc_port_parcel_read_string(sub_parcel_.get(), &tmp_filename);
  if (tmp_filename != nullptr) {
    value = File(tmp_filename);
    free(tmp_filename);
  }

}

void Unit::Write(const TizenEntityPresentation& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetDocument(), p);

    Write(value.GetTemplate(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityPresentation& value) {
  std::string tmp_Document;
  Read(tmp_Document);
  value.SetDocument(tmp_Document);

  std::string tmp_Template;
  Read(tmp_Template);
  value.SetTemplate(tmp_Template);

}

void Unit::Write(const TizenEntityStatus& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetSuccess(), p);

    Write(value.GetReason(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(TizenEntityStatus& value) {
  bool tmp_Success = false;
  Read(tmp_Success);
  value.SetSuccess(tmp_Success);

  std::string tmp_Reason;
  Read(tmp_Reason);
  value.SetReason(tmp_Reason);

}

void Unit::Write(const double& value, rpc_port_parcel_h parcel) {
  auto cb = [value, this](auto* p) {
    rpc_port_parcel_burst_write(p, reinterpret_cast<const unsigned char*>(&value), sizeof(double));

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(double& value) {
  double tmp_value = 0.0;
  rpc_port_parcel_burst_read(sub_parcel_.get(), reinterpret_cast<unsigned char*>(&tmp_value), sizeof(double));
  value = tmp_value;

}

void Unit::Write(const Annotation& value, rpc_port_parcel_h parcel) {
  auto cb = [&value, this](auto* p) {
    Write(value.GetEntityId(), p);

    Write(value.GetEntityType(), p);

    Write(value.GetEntityInfo(), p);

  };

  if (parcel)
    cb(parcel);
  else
    cmds_.push_back(std::move(cb));
}

void Unit::Read(Annotation& value) {
  std::string tmp_EntityId;
  Read(tmp_EntityId);
  value.SetEntityId(tmp_EntityId);

  std::string tmp_EntityType;
  Read(tmp_EntityType);
  value.SetEntityType(tmp_EntityType);

  std::string tmp_EntityInfo;
  Read(tmp_EntityInfo);
  value.SetEntityInfo(tmp_EntityInfo);

}

std::atomic<int> TizenActionView::CallbackBase::seq_num_ { 0 };

TizenActionView::CallbackBase::CallbackBase(int delegate_id, bool once) : id_(delegate_id), once_(once) {
  seq_id_ = seq_num_++;
}

int TizenActionView::CallbackBase::GetId() const {
  return id_;
}

void TizenActionView::CallbackBase::SetId(int id) {
  id_ = id;
}

int TizenActionView::CallbackBase::GetSeqId() const {
  return seq_id_;
}

void TizenActionView::CallbackBase::SetSeqId(int seq_id) {
  seq_id_ = seq_id;
}

bool TizenActionView::CallbackBase::IsOnce() const {
  return once_;
}

void TizenActionView::CallbackBase::SetOnce(bool once) {
  once_ = once;
}

std::string TizenActionView::CallbackBase::GetTag() const {
  return std::to_string(id_) + "::" + std::to_string(seq_id_);
}

void TizenActionView::CallbackBase::SetContext(void* context) {
  context_ = context;
}

void* TizenActionView::CallbackBase::GetContext() const {
  return context_;
}

TizenActionView::ServiceBase::ServiceBase(std::string sender, std::string instance)
: sender_(std::move(sender)),
instance_(std::move(instance)) {
  SetPrivilegeMap();

  dispatch_funcs_ = {
    { static_cast<int>(MethodId::FindById), std::bind(&TizenActionView::ServiceBase::DispatchFindById, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::GetAnnotatedViews), std::bind(&TizenActionView::ServiceBase::DispatchGetAnnotatedViews, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::GetFocusedView), std::bind(&TizenActionView::ServiceBase::DispatchGetFocusedView, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
    { static_cast<int>(MethodId::ToPresentation), std::bind(&TizenActionView::ServiceBase::DispatchToPresentation, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4) },
  };
}

void TizenActionView::ServiceBase::SetPort(rpc_port_h port) {
  port_ = port;

}

void TizenActionView::ServiceBase::Disconnect() {
  if (GetContext() != nullptr) {
    TizenActionView_context_->Disconnect(GetContext());
    SetContext(nullptr);
  } else {
    int ret = rpc_port_disconnect(port_);
    if (ret != RPC_PORT_ERROR_NONE) {
      _E("Failed to disconnect the port. error(%d)", ret);
      return;
    }
  }

  instance_.clear();
  port_ = nullptr;
}

int TizenActionView::ServiceBase::Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel, std::shared_ptr<ServiceBase> service) {
  return Dispatch(port, callback_port, parcel);

}

int TizenActionView::ServiceBase::Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel) {
  rpc_port_parcel_header_h header;
  rpc_port_parcel_get_header(parcel, &header);

  int seq_num = -1;
  rpc_port_parcel_header_get_seq_num(header, &seq_num);

  UnitMap unit_map_;
  unit_map_.Deserialize(parcel);

  int cmd_ = -1;
  unit_map_.Read(1355467489 /*[METHOD]*/, cmd_);

  auto found = dispatch_funcs_.find(cmd_);
  if (found == dispatch_funcs_.end()) {
    _E("Unknown command(%d)", cmd_);
    rpc_port_parcel_destroy(parcel);
    return -1;
  }

  auto& func = found->second;
  func(port, callback_port, seq_num, unit_map_);
  rpc_port_parcel_destroy(parcel);
  return 0;
}

void TizenActionView::ServiceBase::SetPrivilegeMap() {

}

void TizenActionView::ServiceBase::SetParent(const TizenActionView* parent) {
  parent_ = parent;
}

bool TizenActionView::ServiceBase::CheckPrivileges(rpc_port_h port, int method_id) {
  int ret;
  uid_t uid;
  pid_t pid;
  auto found = privilege_map_.find(method_id);
  if (found == privilege_map_.end())
    return true;

  ret = dl_rpc_port_get_peer_info(port, &pid, &uid);
  if(ret == RPC_PORT_ERROR_NONE && uid < kRegularUidMin) {
    _W("Bypass access control. pid(%d), uid(%u)", pid, uid);
    return true;
  }

  for (const auto& privilege : found->second) {
    bool has = false;

    ret = dl_rpc_port_stub_has_privilege_local(
    parent_->GetRaw(), GetSender().c_str(), privilege.c_str(), &has);
    if (ret != 0 || !has) {
      return false;
    }
  }

  return true;
}

void TizenActionView::ServiceBase::DispatchFindById(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::FindById))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    std::string id;
    unit_map.Read(3355 /*id*/, id);

    TizenEntityView v;

    try {
      auto ret_ = FindById(id, v);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(118 /*v*/, v)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionView_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionView::ServiceBase::DispatchGetAnnotatedViews(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::GetAnnotatedViews))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    std::vector<TizenEntityView> views;

    try {
      auto ret_ = GetAnnotatedViews(views);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(112204398 /*views*/, views)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionView_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionView::ServiceBase::DispatchGetFocusedView(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::GetFocusedView))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityView v;

    try {
      auto ret_ = GetFocusedView(v);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(118 /*v*/, v)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionView_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionView::ServiceBase::DispatchToPresentation(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map) {
  rpc_port_parcel_h parcel_;
  rpc_port_parcel_create(&parcel_);

  rpc_port_parcel_header_h header_;
  rpc_port_parcel_get_header(parcel_, &header_);
  rpc_port_parcel_header_set_seq_num(header_, seq_num);
  if (dl_rpc_port_parcel_header_set_tag_ex) {
    dl_rpc_port_parcel_header_set_tag_ex(header_, TIDL_VER_MAJOR,
    TIDL_VER_MINOR, TIDL_VER_PATCH, 2, RPC_PORT_PARCEL_HEADER_LAN_CPP);
  } else {
    rpc_port_parcel_header_set_tag(header_, TIDL_VERSION);
  }

  if (!CheckPrivileges(port, static_cast<int>(MethodId::ToPresentation))) {
    _E("Permission denied");
    RemoteException remote_except(RPC_PORT_ERROR_PERMISSION_DENIED, "Permission denied");
    UnitMap()
    .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, remote_except)
    .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
    .Serialize(parcel_);
  } else {
    TizenEntityView view;
    unit_map.Read(3619493 /*view*/, view);

    TizenEntityPresentation result;

    try {
      auto ret_ = ToPresentation(view, result);
      UnitMap()
      .Write(1497479973 /*[RESULT]*/, ret_)
      .Write(-934426595 /*result*/, result)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);

      } catch (const RemoteException& e) {
      _E("Exception occurs. cause(%d), message(%s)", e.GetCause(), e.GetMessage().c_str());
      UnitMap()
      .Write(-1571313492 /*[REMOTE_EXCEPTION]*/, e)
      .Write(1355467489 /*[METHOD]*/, static_cast<int>(MethodId::__Result))
      .Serialize(parcel_);
    }
  }

  if (GetContext() != nullptr)
    TizenActionView_context_->SendResult(GetContext(), parcel_);
  else
    rpc_port_parcel_send(parcel_, port);
  rpc_port_parcel_destroy(parcel_);
}

void TizenActionView::ServiceBase::SetContext(void* context) {
  context_ = context;
}

void* TizenActionView::ServiceBase::GetContext() const {
  return context_;
}

TizenActionView::TizenActionView() {
  _W("TizenActionView ctor");
  int ret = rpc_port_stub_create(&stub_, "TizenActionView");
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to create stub. error(%d)", ret);
    throw InvalidIOException();
  }
  rpc_port_stub_add_connected_event_cb(stub_, OnConnectedCb, this);
  rpc_port_stub_add_disconnected_event_cb(stub_, OnDisconnectedCb, this);
  rpc_port_stub_add_received_event_cb(stub_, OnReceivedCb, this);

  TizenActionView_context_ = std::make_unique<LocalExecution>("TizenActionView", this);
}

TizenActionView::~TizenActionView() {
  _W("TizenActionView dtor");
  for (auto& service : services_) {
    if(!service->GetInstance().empty())
    service->OnTerminate();

    if (TizenActionView_context_ && service->GetContext())
      TizenActionView_context_->Disconnect(service->GetContext());
  }

  TizenActionView_context_.reset();
  if (stub_ != nullptr)
    rpc_port_stub_destroy(stub_);
}

void TizenActionView::Listen(std::shared_ptr<TizenActionView::ServiceBase::Factory> service_factory) {
  service_factory_ = std::move(service_factory);
  int ret = rpc_port_stub_listen(stub_);
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to listen stub. error(%d)", ret);
    if (ret == RPC_PORT_ERROR_INVALID_PARAMETER || ret == RPC_PORT_ERROR_IO_ERROR)
      throw InvalidIOException();
  }

  TizenActionView_context_->SetListening(true);
}
void TizenActionView::OnConnectedCb(const char* sender, const char* instance, void* user_data) {
  auto* handle = static_cast<TizenActionView*>(user_data);
  auto service = handle->service_factory_->CreateService(sender, instance);

  service->SetParent(handle);
  rpc_port_h port;
  int ret = rpc_port_stub_get_port(handle->stub_, RPC_PORT_PORT_CALLBACK, instance, &port);
  if (ret != RPC_PORT_ERROR_NONE) {
    _E("Failed to get port. error(%d)", ret);
    return;
  }

  service->SetPort(port);
  service->OnCreate();
  handle->services_.emplace_back(std::move(service));
}

void TizenActionView::OnDisconnectedCb(const char* sender, const char* instance, void* user_data) {
  auto* handle = static_cast<TizenActionView*>(user_data);
  auto iter = handle->services_.begin();
  while (iter != handle->services_.end()) {
    if ((*iter)->GetInstance() == instance) {
      (*iter)->OnTerminate();
      iter = handle->services_.erase(iter);
      break;
    }

    iter++;
  }
}

int TizenActionView::OnReceivedCb(const char* sender, const char* instance, rpc_port_h port, void* user_data) {
  auto* handle = static_cast<TizenActionView*>(user_data);
  std::shared_ptr<ServiceBase> service;
  for (auto& iter : handle->services_) {
    if (iter->GetInstance() == instance) {
      service = iter;
      break;
    }
  }

  if (service.get() == nullptr) {
    _E("Failed to find TizenActionView context. instance(%s)", instance);
    return -1;
  }

  rpc_port_h callback_port;
  int ret = rpc_port_stub_get_port(handle->stub_, RPC_PORT_PORT_CALLBACK, instance, &callback_port);
  if (ret != 0) {
    _E("Failed to get callback port. error(%d)", ret);
    return -1;
  }

  rpc_port_parcel_h parcel;
  ret = rpc_port_parcel_create_from_port(&parcel, port);
  if (ret != 0) {
    _E("Failed to create parcel from port. error(%d)", ret);
    return ret;
  }

  return service->Dispatch(port, callback_port, parcel, service);
}

void TizenActionView::OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) {
  auto service = service_factory_->CreateService(sender, instance);
  service->SetParent(this);
  service->SetContext(context);
  service->OnCreate();
  services_.emplace_back(std::move(service));
  TizenActionView_context_->Connect(context, sync);
}

void TizenActionView::OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) {
  auto iter = services_.begin();
  while (iter != services_.end()) {
    if ((*iter)->GetInstance() == instance) {
      (*iter)->OnTerminate();
      iter = services_.erase(iter);
      break;
    }

    iter++;
  }

  TizenActionView_context_->Disconnect(context);
}

void TizenActionView::OnLocalReceived(void* context, rpc_port_parcel_h parcel) {
  std::shared_ptr<ServiceBase> service;
  for (auto& iter : services_) {
    if (iter->GetContext() == context) {
      service = iter;
      break;
    }
  }

  if (service.get() == nullptr) {
    _E("Failed to find TizenActionView context. context(%p)", context);
    return;
  }

  service->Dispatch(nullptr, nullptr, parcel, service);
}

}  // namespace stub
}  // namespace implview
}  // namespace rpc_port

EXPORT_API int rpc_port_stub_tizen_action_view_lem_TizenActionView_connect(void* context, const char* sender, const char* instance, bool sync) {
  if (TizenActionView_context_.get() == nullptr || !TizenActionView_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  std::string sender_str(sender);
  std::string instance_str(instance);
  if (gettid() == getpid()) {
    TizenActionView_context_->OnConnected(context, sender, instance, sync);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, sender_str, instance_str, sync] {
    TizenActionView_context_->OnConnected(context, sender_str, instance_str, sync);
  });
  if (!IdleAddOnce(TizenActionView_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}

EXPORT_API int rpc_port_stub_tizen_action_view_lem_TizenActionView_disconnect(void* context, const char* sender, const char* instance) {
  if (TizenActionView_context_.get() == nullptr || !TizenActionView_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  std::string sender_str(sender);
  std::string instance_str(instance);
  if (gettid() == getpid()) {
    TizenActionView_context_->OnDisconnected(context, sender, instance);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, sender_str, instance_str] {
    TizenActionView_context_->OnDisconnected(context, sender_str, instance_str);
  });
  if (!IdleAddOnce(TizenActionView_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}

EXPORT_API int rpc_port_stub_tizen_action_view_lem_TizenActionView_send(void* context, rpc_port_parcel_h parcel) {
  if (TizenActionView_context_.get() == nullptr || !TizenActionView_context_->IsListening()) {
    _E("Server is not ready");
    return RPC_PORT_ERROR_IO_ERROR;
  }

  rpc_port_parcel_h cloned_parcel = nullptr;
  dl_rpc_port_parcel_clone(&cloned_parcel, parcel);
  if (gettid() == getpid()) {
    TizenActionView_context_->OnReceived(context, cloned_parcel);
    return RPC_PORT_ERROR_NONE;
  }

  auto* func = new std::function<void()>([context, cloned_parcel] {
    TizenActionView_context_->OnReceived(context, cloned_parcel);
  });
  if (!IdleAddOnce(TizenActionView_context_->GetContext(), func)) {
    delete func;
    return RPC_PORT_ERROR_OUT_OF_MEMORY;
  }

  return RPC_PORT_ERROR_NONE;
}
