/**
 * Generated by tidlc 2.9.3.
 */

#pragma once

#include <bundle.h>
#include <rpc-port-parcel.h>
#include <rpc-port.h>
#include <glib.h>

#include <atomic>
#include <exception>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <queue>

namespace rpc_port {
namespace implview {

class RawFdWrapper {
 public:
  RawFdWrapper() : fd_(-1) {}
  RawFdWrapper(int fd) : fd_(fd) {}

  int Get() const { return fd_; }
  void Set(int fd) { fd_ = fd; }

 private:
  int fd_;
};

class LocalExecution {
 public:
  class IEvent {
   public:
    virtual ~IEvent() = default;
    virtual void OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) = 0;
    virtual void OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) = 0;
    virtual void OnLocalReceived(void* context, rpc_port_parcel_h parcel) = 0;
  };

  LocalExecution(std::string port_name, IEvent* listener);
  virtual ~LocalExecution() = default;

  void Connect(void* context, bool sync);
  void Disconnect(void* context);
  void SendResult(void* context, rpc_port_parcel_h parcel);
  void InvokeCallback(void* context, rpc_port_parcel_h parcel);

  void OnConnected(void* context, const std::string& sender, const std::string& instance, bool sync);
  void OnDisconnected(void* context, const std::string& sender, const std::string& instance);
  void OnReceived(void* context, rpc_port_parcel_h parcel);

  void SetListening(bool listening);
  bool IsListening() const;

  bool LoadSymbols();
  GMainContext* GetContext() const;

 private:
  using ProxyConnectFunc = int (*)(void*, bool);
  using ProxyDisconnectFunc = int (*)(void*);
  using ProxySendResultFunc = int (*)(void*, rpc_port_parcel_h);
  using ProxyInvokeCallbackFunc = int (*)(void*, rpc_port_parcel_h);

 private:
  std::string port_name_;
  IEvent* listener_;
  bool listening_ = false;
  bool loaded_ = false;
  ProxyConnectFunc connect_func_ = nullptr;
  ProxyDisconnectFunc disconnect_func_ = nullptr;
  ProxySendResultFunc send_result_func_ = nullptr;
  ProxyInvokeCallbackFunc invoke_callback_func_ = nullptr;
  std::unique_ptr<GMainContext, decltype(g_main_context_unref)*> context_;
};

class Bundle final {
 public:
  Bundle();
  explicit Bundle(bundle* handle, bool copy = true, bool own = true);
  Bundle(std::string raw);
  ~Bundle();

  Bundle(const Bundle& b);
  Bundle& operator = (const Bundle& b);
  Bundle(Bundle&& b) noexcept;
  Bundle& operator = (Bundle&&) noexcept;

  bundle* GetHandle() const;
  bundle* Detach();

 private:
  bundle* handle_;
  bool own_ = true;
};

class File final {
 public:
  File(std::string filename = "");

  const std::string& GetFileName() const;
  int Share(rpc_port_h port);

 private:
  std::string filename_;
};

class TizenEntityPresentation {
 public:

  TizenEntityPresentation();
  TizenEntityPresentation(std::string Document, std::string Template);

  const std::string& GetDocument() const;
  void SetDocument(std::string Document);

  const std::string& GetTemplate() const;
  void SetTemplate(std::string Template);

  std::string ToJson() const;
 private:
  std::string Document_;
  std::string Template_;

};

class TizenEntityStatus {
 public:

  TizenEntityStatus();
  TizenEntityStatus(bool Success, std::string Reason);

  bool GetSuccess() const;
  void SetSuccess(bool Success);

  const std::string& GetReason() const;
  void SetReason(std::string Reason);

  std::string ToJson() const;
 private:
  bool Success_;
  std::string Reason_;

};

class TizenEntity {
 public:

  TizenEntity();
  TizenEntity(std::string Id, std::string Extra);

  const std::string& GetId() const;
  void SetId(std::string Id);

  const std::string& GetExtra() const;
  void SetExtra(std::string Extra);

  std::string ToJson() const;
 private:
  std::string Id_;
  std::string Extra_;

};

class ScreenBounds {
 public:

  ScreenBounds();
  ScreenBounds(double X, double Y, double Width, double Height);

  double GetX() const;
  void SetX(double X);

  double GetY() const;
  void SetY(double Y);

  double GetWidth() const;
  void SetWidth(double Width);

  double GetHeight() const;
  void SetHeight(double Height);

  std::string ToJson() const;
 private:
  double X_;
  double Y_;
  double Width_;
  double Height_;

};

class WindowBounds {
 public:

  WindowBounds();
  WindowBounds(double X, double Y, double Width, double Height);

  double GetX() const;
  void SetX(double X);

  double GetY() const;
  void SetY(double Y);

  double GetWidth() const;
  void SetWidth(double Width);

  double GetHeight() const;
  void SetHeight(double Height);

  std::string ToJson() const;
 private:
  double X_;
  double Y_;
  double Width_;
  double Height_;

};

class Annotation {
 public:

  Annotation();
  Annotation(std::string EntityId, std::string EntityType, std::string EntityInfo);

  const std::string& GetEntityId() const;
  void SetEntityId(std::string EntityId);

  const std::string& GetEntityType() const;
  void SetEntityType(std::string EntityType);

  const std::string& GetEntityInfo() const;
  void SetEntityInfo(std::string EntityInfo);

  std::string ToJson() const;
 private:
  std::string EntityId_;
  std::string EntityType_;
  std::string EntityInfo_;

};

class TizenEntityView : public TizenEntity {
 public:

  TizenEntityView();
  TizenEntityView(std::string Id, std::string Extra, std::string Type, std::string Description, ScreenBounds ScreenBounds, WindowBounds WindowBounds, bool IsFocused, bool IsEnabled, Annotation Annotation);

  const std::string& GetType() const;
  void SetType(std::string Type);

  const std::string& GetDescription() const;
  void SetDescription(std::string Description);

  const ScreenBounds& GetScreenBounds() const;
  void SetScreenBounds(ScreenBounds ScreenBounds);

  const WindowBounds& GetWindowBounds() const;
  void SetWindowBounds(WindowBounds WindowBounds);

  bool GetIsFocused() const;
  void SetIsFocused(bool IsFocused);

  bool GetIsEnabled() const;
  void SetIsEnabled(bool IsEnabled);

  const Annotation& GetAnnotation() const;
  void SetAnnotation(Annotation Annotation);

  std::string ToJson() const;
 private:
  std::string Type_;
  std::string Description_;
  ScreenBounds ScreenBounds_;
  WindowBounds WindowBounds_;
  bool IsFocused_;
  bool IsEnabled_;
  Annotation Annotation_;

};

namespace stub {

class UnitMap;

class Exception : public std::exception {
 public:
  virtual const char* what() const noexcept override {
    return "RPC Port Exception";
  }
};
class NotConnectedSocketException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Not connected socket";
  }
};
class InvalidProtocolException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid protocol";
  }
};
class InvalidIOException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid I/O";
  }
};
class PermissionDeniedException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Permission denied";
  }
};
class InvalidIDException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid ID";
  }
};
class InvalidArgumentException : public Exception {
 public:
  const char* what() const noexcept override {
    return "Invalid argument";
  }
};

class RemoteException : public Exception {
 public:
  RemoteException();
  RemoteException(std::string message);
  RemoteException(int cause, std::string message);

  int GetCause() const;
  const std::string& GetMessage() const;

 private:
  int cause_ = 0;
  std::string message_;
};

class TizenActionView : public LocalExecution::IEvent {
 public:

  class ServiceBase;

  class CallbackBase {
   public:
    CallbackBase(int delegate_id, bool once);
    CallbackBase() = default;
    virtual ~CallbackBase() = default;

    int GetId() const;
    void SetId(int id);
    int GetSeqId() const;
    void SetSeqId(int seq_id);
    bool IsOnce() const;
    void SetOnce(bool once);

    std::string GetTag() const;

    void SetContext(void* context);
    void* GetContext() const;

   private:
    static std::atomic<int> seq_num_;
    int id_ = 0;
    int seq_id_ = 0;
    bool once_ = false;
    void* context_ = nullptr;
  };

  class ServiceBase : public std::enable_shared_from_this<ServiceBase> {
   public:
    class Factory {
     public:
      virtual ~Factory() = default;

      /// <summary>
      /// The method for making service instances
      /// </summary>
      /// <param name="sender">The client app ID</param>
      /// <param name="instance">The client instance ID</param>
      virtual std::unique_ptr<ServiceBase> CreateService(std::string sender, std::string instance) = 0;
    };

    virtual ~ServiceBase() = default;

    /// <summary>
    /// Gets client app ID
    /// </summary>
    const std::string& GetSender() const {
      return sender_;
    }

    /// <summary>
    /// Gets client instance ID
    /// </summary>
    const std::string& GetInstance() const {
      return instance_;
    }

    /// <summary>
    /// Sets the client app port
    /// </summary>
    /// <param name="port">The port of the client</param>
    void SetPort(rpc_port_h port);

    /// <summary>
    /// Disconnects from the client app
    /// </summary>
    /// <exception cref="InvalidIOException">
    /// Thrown when internal I/O error happen.
    /// </exception>
    void Disconnect();

    /// <summary>
    /// This method will be called when the client is connected
    /// </summary>
    virtual void OnCreate() = 0;

    /// <summary>
    /// This method will be called when the client is disconnected
    /// </summary>
    virtual void OnTerminate() = 0;

    void SetContext(void* context);
    void* GetContext() const;
    void SetParent(const TizenActionView* parent);
    int Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel, std::shared_ptr<ServiceBase> service);
    int Dispatch(rpc_port_h port, rpc_port_h callback_port, rpc_port_parcel_h parcel);

    virtual TizenEntityStatus FindById(std::string id, TizenEntityView& view) = 0;
    virtual TizenEntityStatus GetAnnotatedViews(std::vector<TizenEntityView>& views) = 0;
    virtual TizenEntityStatus GetFocusedView(TizenEntityView& view) = 0;
    virtual TizenEntityStatus ToPresentation(TizenEntityView view, TizenEntityPresentation& result) = 0;

   protected:
    ServiceBase(std::string sender, std::string instance);

   private:
    using DispatchFunc = std::function<void(rpc_port_h, rpc_port_h, int, const UnitMap&)>;

    void SetPrivilegeMap();
    bool CheckPrivileges(rpc_port_h port, int method_id);
    void DispatchFindById(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchGetAnnotatedViews(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchGetFocusedView(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);
    void DispatchToPresentation(rpc_port_h port, rpc_port_h callback_port, int seq_num, const UnitMap& unit_map);

   private:
    std::string sender_;
    std::string instance_;
    rpc_port_h port_ = nullptr;
    std::unordered_map<int, DispatchFunc> dispatch_funcs_;
    std::unordered_map<int, std::vector<std::string>> privilege_map_;
    void* context_ = nullptr;
    const TizenActionView* parent_ = nullptr;
  };

  TizenActionView();
  ~TizenActionView();

  /// <summary>
  /// Listens to client apps
  /// </summary>
  /// <param name="service_factory">The factory object for making service instances</param>
  /// <exception cref="InvalidIOException">
  /// Thrown when internal I/O error happen.
  /// </exception>
  void Listen(std::shared_ptr<ServiceBase::Factory> service_factory);
  /// <summary>
  /// Gets service objects which are connected
  /// </summary>
  /// <returns>The list of service objects which are connected</returns>
  const std::list<std::shared_ptr<ServiceBase>>& GetServices() const {
    return services_;
  }

  rpc_port_stub_h GetRaw() const {
    return stub_;
  }

 private:
  enum class MethodId : int {
    __Result = 0,
    __Callback = 1,
    FindById = 2,
    GetAnnotatedViews = 3,
    GetFocusedView = 4,
    ToPresentation = 5,
  };

  static void OnConnectedCb(const char* sender, const char* instance, void* user_data);
  static void OnDisconnectedCb(const char* sender, const char* instance, void* user_data);
  static int OnReceivedCb(const char* sender, const char* instance, rpc_port_h port, void* user_data);

  void OnLocalConnected(void* context, const std::string& sender, const std::string& instance, bool sync) override;
  void OnLocalDisconnected(void* context, const std::string& sender, const std::string& instance) override;
  void OnLocalReceived(void* context, rpc_port_parcel_h parcel) override;

 private:
  rpc_port_stub_h stub_ = nullptr;
  std::shared_ptr<ServiceBase::Factory> service_factory_;
  std::list<std::shared_ptr<ServiceBase>> services_;
};

}  // namespace stub
}  // namespace implview
}  // namespace rpc_port

