#ifndef __DALI_INTERNAL_BASE_PERFORMANCE_INTERFACE_H__
#define __DALI_INTERNAL_BASE_PERFORMANCE_INTERFACE_H__

/*
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

namespace Dali
{

namespace Internal
{

namespace Adaptor
{

/**
 * Abstract Performance Interface.
 * Used by the Adaptor to store performance metrics.
 *
 */
class PerformanceInterface
{
public:

  typedef unsigned short ContextId;   ///< Type to represent a context ID

  /**
   * bitmask of logging options
   */
  enum LogLevel
  {
    DISABLED             = 0,
    ENABLED              = 1 << 0, ///< Bit 0, log all
    LOG_UPDATE_RENDER    = 1 << 1, ///< Bit 1, log update and render times
    LOG_EVENT_PROCESS    = 1 << 2, ///< Bit 2, log event process times
    LOG_EVENTS_TO_KERNEL = 1 << 3  ///< Bit 3, log all events to kernel trace
  };

  /**
   * enum for difference performance markers.
   * Please modify the name lookup table in performance-interface.cpp
   * file if adding new markers.
   */
  enum MarkerType
  {
    VSYNC     = 0,        ///< V-Sync
    UPDATE_START ,        ///< Update start
    UPDATE_END   ,        ///< Update end
    RENDER_START ,        ///< Render start
    RENDER_END   ,        ///< Render end
    SWAP_START   ,        ///< SwapBuffers Start
    SWAP_END     ,        ///< SwapBuffers End
    PROCESS_EVENTS_START, ///< Process events start (e.g. touch event)
    PROCESS_EVENTS_END,   ///< Process events end
    PAUSED       ,        ///< Pause start
    RESUME       ,        ///< Resume start
    START        ,        ///< The start of custom tracking
    END                   ///< The end of custom tracking
  };

  /**
   * Constructor.
   */
  PerformanceInterface() {}

  /**
   * Virtual destructor
   */
  virtual ~PerformanceInterface() {};

  /**
   * Add a new context with a given name
   *
   * @param[in] name The name of the context
   * @return Return the unique id for this context
   */
  virtual ContextId AddContext( const char* name ) = 0;

  /**
   * Remove a context from use
   *
   * @param[in] contextId The ID of the context to remove
   */
  virtual void RemoveContext( ContextId contextId ) = 0;

  /**
   * Add a performance marker
   * This function can be called from ANY THREAD.
   * The default context 0 Event/Update/Render is assumed.
   * @param markerType performance marker type
   */
  virtual void AddMarker( MarkerType markerType ) = 0;

  /**
   * Add a performance marker
   * This function can be called from ANY THREAD.
   * @param markerType performance marker type
   * @param contextId The context of the marker. This must be one generated by AddContext.
   */
  virtual void AddMarker( MarkerType markerType, ContextId contextId ) = 0;

  /**
   * Set the logging level and frequency
   * @param level 0 = disabled, 1 = enabled
   * @param logFrequency how often to log out in seconds
   */
  virtual void SetLogging( unsigned int level, unsigned int logFrequency) = 0;

  /**
   * Set the logging frequency
   *
   * @param logFrequency how often to log out in seconds
   */
  virtual void SetLoggingFrequency( unsigned int logFrequency, ContextId contextId ) = 0;

  /**
   * Set logging on or off for a particular context
   *
   * @param[in] enable Enable logging or not
   * @param[in] contextId The id of the context to log. This must be one generated by AddContext.
   */
  virtual void EnableLogging( bool enable, ContextId contextId ) = 0;

private:

  // Undefined copy constructor.
  PerformanceInterface( const PerformanceInterface& );

  // Undefined assignment operator.
  PerformanceInterface& operator=( const PerformanceInterface& );

};

} // namespace Internal

} // namespace Adaptor

} // namespace Dali

#endif
